### ISSUE TITLE
shopifyQuery error:  ClientError: undefined

### ISSUE THREAD

**Issue by felix-le** [AbeCole/gatsby-source-shopify-admin#28]
Hi, 
I got this issue shopifyQuery error:  ClientError: undefined

Thanks

**Comment by AbeCole** [comment]
Hi,

Can be a bit hard to debug issues as the Shopify client isn't always the clearest. Such as in this case the error returned is simply "undefined", that may be because the fetch library we use ([graphql-request](https://github.com/prisma-labs/graphql-request)) might not be handling the error correctly or it might be that Shopify's API isn't returning a valid error. 

Having looked at some issues on the graphql-request library it seems like this might be related to how errors are handled/thrown in the library itself, specifically related to the `rawRequest` method.

If you can provide a repo of your code I can try run it myself locally to see if I can work out the issue.

**Comment by AbeCole** [comment]
Closing for now as no further information and both Gatsby & this plugin have moved on a bit since this was opened.
